### ISSUE TITLE
Organisation Logo not being recognised in Rich Results

### ISSUE THREAD

**Issue by harlan-zw** [harlan-zw/nuxt-schema-org#16]
### Describe the bug

For whatever reason, it seems like Google isn't recognizing the logo when it's set as its own node.

### System Info

```Shell
.
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AleeeKoi** [comment]
Hello, any updates?

**Comment by harlan-zw** [comment]
Available in the latest version :)
