### ISSUE TITLE
How to set up in nuxt?

### ISSUE THREAD

**Issue by geoHeil** [harlan-zw/nuxt-schema-org#20]
### Details

The main documentation refers to https://unhead-schema-org.harlanzw.com/guide/getting-started/setup:

```
import { SchemaOrgUnheadPlugin } from '@unhead/schema-org'createHead({  plugins: [    SchemaOrgUnheadPlugin()  ]})
```

however, inside NUXT I do not find these settings.

https://unhead-schema-org.harlanzw.com/integrations/nuxt/module links a more direct NUXT integration. However, for me on 3.5 this does not render any of the JSON+LD metadata tags.

**Comment by geoHeil** [comment]
The example https://stackblitz.com/edit/nuxt-starter-6n6tsz?file=app.vue works in stackblitz. However, for me when creating an empty page (hello.vue) and pasting the contents of index.vue, adding all the dependencies and configuration plus setting the global nodes I cannot get any graph/schema.org metadata to render.

**Comment by geoHeil** [comment]
When using https://github.com/ymmooot/nuxt-jsonld instead - the JSON+LD is rendered instantly.

**Comment by harlan-zw** [comment]
Hi, sorry for the very long delay in responding. The Nuxt usage should be a lot clearer now and the docs are located at https://nuxtseo.com/schema-org/getting-started/installation

I'll be improving this as well as I move to the v3 release.
