### ISSUE TITLE
Interface of LocalBusiness is empty.

### ISSUE THREAD

**Issue by ILLuMiNaTe7** [harlan-zw/nuxt-schema-org#22]
### Describe the bug

This is relatively minor. But it seems the LocalBusiness interface is empty and has no defined parameters.

`interface LocalBusiness extends LocalBusinessSimple {}`

**Comment by harlan-zw** [comment]
Hi, sorry for the delay. The types are on `LocalBusinessSimple`, the interface here exists to make augmenting the types easier.
