### ISSUE TITLE
`InLanguage` is not resolved for `SchemaOrgArticle`

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-schema-org#29]
### Describe the bug

Hello,

In the documentation you said that the article must inherit form default config ,https://unhead-schema-org.harlanzw.com/schema/article#defaults. But when using it in a nuxt project, it does not work.

For the reproduction:
1. Install deps with `pnpm install`
2. Go to `/blog/2023-08-15-h3-towards-the-edge-of-the-web`
3. Inspect page and the section `#article` in `application/json+ld`

### Reproduction

https://github.com/unjs/website/pull/38

**Comment by harlan-zw** [comment]
This is fixed in v3 :)
