### ISSUE TITLE
Argument of type '"schema-org:meta"' is not assignable to parameter of type 'HookKeys<RuntimeNuxtHooks>'.ts

### ISSUE THREAD

**Issue by harlan-zw** [harlan-zw/nuxt-schema-org#33]
### Describe the bug

moved from https://github.com/nuxt/nuxt/issues/22692

**Comment by harlan-zw** [comment]
This will be fixed in v3 which will be released soon.

**Comment by Quineone** [comment]
Still have this issue in this version  "nuxt-schema-org": "^3.2.1"

**Comment by harlan-zw** [comment]
Can you try deleting your .nuxt folder and re-generating it and then see if the types are working? They are only injected with the rest of the nuxt types.

**Comment by Quineone** [comment]
@harlan-zw thank for the reply, but tried, seems doesn't work.

**Comment by harlan-zw** [comment]
You're right, I typed this incorrectly as a build-time hook. I've updated the types and it should be working in v3.2.3 :crossed_fingers:

**Comment by Quineone** [comment]
Awesome! Thank you!
