### ISSUE TITLE
Add Episode and AudioObject Schema

### ISSUE THREAD

**Issue by ebrawer** [harlan-zw/nuxt-schema-org#35]
### Clear and concise description of the problem

I need the two following schema objects for a podcast:

Episode: https://schema.org/Episode
AudioObject: https://schema.org/AudioObject

### Suggested solution

**Episode Schema:**
The primary schema type for a podcast episode is the Episode schema. This schema can capture details specific to the episode.
@type: "Episode"
name: The title of the episode.
description: A brief summary or description of the episode.
datePublished: The release date of the episode.
episodeNumber: The episode number, if applicable.
url: The URL of the episode page.
image: The cover image or thumbnail for the episode.
partOfSeries: A reference to the podcast series, typically using the CreativeWorkSeries or RadioSeries schema type.

**AudioObject Schema:**
To represent the actual audio file of the podcast episode, use the AudioObject schema.
@type: "AudioObject"
contentUrl: Direct link to the audio file.
duration: Duration of the audio file (e.g., "PT1H30M" for 1 hour 30 minutes).
encodingFormat: The format of the audio file, like "audio/mpeg" for an MP3.

**Comment by harlan-zw** [comment]
Going to track this in Unhead, where there is already an issue. See https://github.com/harlan-zw/nuxt-schema-org/issues/35
