### ISSUE TITLE
Module breaks non-build `nuxi` commands like `prepare` and `typecheck`

### ISSUE THREAD

**Issue by jonasolesen** [harlan-zw/nuxt-schema-org#36]
### Describe the bug

When running commands like `nuxi prepare` and `nuxi typecheck` with `nuxt-schema-org@3.1.0` or later, I get the following error:

`Cannot start nuxt:  Cannot read properties of undefined (reading 'PROD')`

The error originates from [this](https://github.com/harlan-zw/nuxt-schema-org/blob/5f59da5c8753063dbda4ae49d5c8b1fdbfa3f875/src/module.ts#L65) line reading `import.meta.env.PROD`. It works during `nuxi dev`, so I guess it could be a matter of Vite not being available during non-build commands, or at least not at the time of calling the module's `defaults` hook 🤷‍♂️ 

### Reproduction

I cannot provide a minimal reproduction at this point, but it seems like it might be a simple fix. If this is not the case, I can take a look at creating a proper reproduction

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.2`
- Package Manager:  `pnpm@8.9.2`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
(Don't know why `nuxi info` doesn't show any modules, but I'm using both `nuxt-schema-org` and `nuxt-simple-sitemap`)
```

**Comment by jonasolesen** [comment]
I may have been wrong when I said it still worked during `nuxi dev`, or my initial run may have behaved differently somehow, but all of the following `nuxi` commands fail for me now: `build`, `dev`, `generate`, `prepare`, and `typecheck`.

**Comment by karlstulik** [comment]
Ok, I'm also getting this error but I just installed this for the first time now.

**Comment by yk-sgr** [comment]
Same for me

**Comment by illyaBendik** [comment]
As workaround, I dowgrade nuxt-schema-org to 3.0.0

**Comment by harlan-zw** [comment]
Sorry! looks like a weird bug, not sure why the CI didn't pick it up.

Please upgrade to 3.1.2
