### ISSUE TITLE
fix: context is dropped in v3.1

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/nuxt-schema-org#37]
### Describe the bug

Since `v3.1(.2)` the Nuxt context is dropped supposedly due to some async functionality. This leads to errors like `[nuxt] [request error] [unhandled] [500] router.currentRoute.value is undefined`, see reproduction. `v3.0.1` works fine.

Remind me of https://github.com/nuxt/nuxt/issues/23074.

### Reproduction

https://stackblitz.com/edit/github-fcnmuy?file=package.json

### System / Nuxt Info

```Shell
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  nuxt-schema-org@3.1.2
- Build Modules:    -
```

**Comment by harlan-zw** [comment]
Thanks! Please try 3.1.3
