### ISSUE TITLE
DefinedTerm & DefinedTermSet Nodes

### ISSUE THREAD

**Issue by methodev** [harlan-zw/nuxt-schema-org#38]
As a developer using [nuxt-schema-org](https://github.com/harlan-zw/nuxt-schema-org) with [Nuxt 3](https://nuxt.com/), I want to implement schema that includes [DefinedTerm](https://schema.org/DefinedTerm) & [DefinedTermSet](https://schema.org/DefinedTermSet) types.

However, currently, nodes for the DefinedTerm & DefinedTermSet types are not supported.

Are there any plans of adding more nodes in the near future, including DefinedTerm & DefinedTermSet?

Thanks,
Martin

**Comment by harlan-zw** [comment]
Hi @methodev. Thanks for the issue.

The scope of the official nodes are ones that are needed for Google Rich Results. `useSchemaOrg` support any js objects as schema nodes. I've just improved the documentation on this here https://nuxtseo.com/schema-org/guides/nodes

Will close as it's not something planned but let me know if the above isn't clear.
