### ISSUE TITLE
ScrollBehavior issue

### ISSUE THREAD

**Issue by or2e** [harlan-zw/nuxt-schema-org#39]
### Describe the bug

Hey!
You have a great library.

I have a few question, I don't know if it's a bug or a feature.

I was experimenting with the new option in nuxt `definePageMeta.scrollToTop`, and noticed that it is called several times if the `schema-org` module is activated.

Also, the `scrollToTop` function is called on the server side.
This behavior is also observed with `npm run build && npm run preview`

I tried changing the `reactive` option, it got better, instead of 3 triggers, it got 2, also it's still being called on the server.

<details>
  <summary>npm run dev, reactivity:default, server:1, client:3</summary>
  
  ![image](https://github.com/harlan-zw/nuxt-schema-org/assets/33551334/8f6ea361-5968-4870-b201-c16e821857ae)
</details>

<details>
  <summary>npm run dev, reactivity:false, server:1, client:1</summary>
  
  ![image](https://github.com/harlan-zw/nuxt-schema-org/assets/33551334/a11cf999-74b9-42a4-986f-73ed56ffbaa8)
</details>

<details>
  <summary>npm run preview, reactivity:default, server:1, client:2</summary>
  
  ![image](https://github.com/harlan-zw/nuxt-schema-org/assets/33551334/b153fccf-aa51-4154-a2c0-5818f3dcd42e)
</details>

<details>
  <summary>npm run preview, reactivity:false, server:1, client:2</summary>
  
  ![image](https://github.com/harlan-zw/nuxt-schema-org/assets/33551334/c3b71fd2-b731-4a96-9161-eb42fbd03b24)
</details>

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wxf2mo

**Comment by harlan-zw** [comment]
Hey @or2e, good catch! Thank you for the detailed issue.

This should hopefully be fixed in 3.1.6.
