### ISSUE TITLE
fix: key `schema-org-graph` missing from script

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/nuxt-schema-org#40]
### Describe the bug

The `<script type="application/ld+json"` previously had an `id="schema-org-graph"` but seems to not have that anymore. I used it to do a regression test on that script element.

### Reproduction

https://stackblitz.com/edit/github-zwjgfp?file=package.json,app.vue,nuxt.config.ts

### System / Nuxt Info

```Shell
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  nuxt-schema-org@3.1.8
- Build Modules:    -
```

**Comment by dargmuesli** [comment]
It's there in `3.1.6` but gone in `3.1.7`.

**Comment by harlan-zw** [comment]
Thanks for flagging this, the id was something that isn't used internally and I figured it's not polluting the DOM with it.

What do you think should be the resolution on this? I could add an option on the module that will let you modify all of the attributes of the script tag.

**Comment by harlan-zw** [comment]
Okay so in v3.2.0 `scriptOptions` is available that by default will be `{ id: 'schema-org-graph', }`, if not provided.

You can pass in `false` or any data, including `tagPosition`, `tagPriority`, etc. and it should just work.

This version also fixed Logos in Google Rich Results

**Comment by dargmuesli** [comment]
Thank you! :heart:
