### ISSUE TITLE
@unhead/schema-org incompatibility

### ISSUE THREAD

**Issue by jekuer** [harlan-zw/nuxt-schema-org#41]
### Describe the bug

Upgrading from 3.1.3 to latest 3.2.0, I get the error `Failed to resolve import "@unhead/schema-org/vue" from "app.vue" . Does the file exist?` when running `npm run dev` or build.

At app.vue, I define the base information as per your documentation.

It seems that there is some dependency mismatch. Any spontaneous idea what could cause that?

I am using nuxt 3.7.4.

**Comment by tmlmt** [comment]
This happened to me a couple of times too. Not sure what happens, but at least I got it solved by deleting the node_modules directory and reinstalling packages with `npm i`

**Comment by harlan-zw** [comment]
Are you still having issues with the latest version / latest Nuxt?

It's hard to diagnose the issue, can you confirm you have `typescript` as a dependency and what version

**Comment by jekuer** [comment]
Hi,

Sorry for not keeping this updated.
I have no more blocking issues.
On generate it complained about the manifest.json, which gets injected by nuxt pwa. I simply excluded this from prerendering (where it is not needed anyway) and now it all runs smoothly.

Best,
Jens

**Comment by jekuer** [comment]
Maybe it just was a hickup while upgrading...
Anyhow - this modules seems fine.

**Comment by tmlmt** [comment]
In my case, it was not an upgrade, but when installing and trying to use the module for the first time (I think). Was it already present by another module requiring it, I'm not sure. 
Similarly as with Jens, it was complaining with `@unhead/schema-org/*` files not existing. And indeed, when looking inside `node_modules`, there were some files, but the `schema-org` directory was absent, for some reason.

**Comment by harlan-zw** [comment]
Hm strange, thanks for the details. Will close for now but will keep an eye on it
