### ISSUE TITLE
multiple schema orgs

### ISSUE THREAD

**Issue by djixadin** [harlan-zw/nuxt-schema-org#44]
### Details

is it possible to use multiple schema orgs .. i have this usecase 

```
const schemaOrgDefinition: any = {
  '@type': 'NewsArticle',
...restOfMySchema
}

  useSchemaOrg([defineArticle(schemaOrgDefinition)])

if (isLiveNews) {
  schemaOrgDefinition['@type'] = 'LiveBlogPosting'
  schemaOrgDefinition.coverageStartTime = singleNews.publish_date

  const estimatedEndTime = new Date(singleNews.publish_date)
  estimatedEndTime.setHours(estimatedEndTime.getHours() + 4)

  schemaOrgDefinition.coverageEndTime = estimatedEndTime.toISOString()
  useSchemaOrg([schemaOrgDefinition])
}

```

**Comment by harlan-zw** [comment]
Sure, it dedupes based on the `@id`, if you don't provide an `@id` it automatically generates it. For top-level schema.org it generates a single id per node type, for example article will have an id of `#article`

So you would do something like

```ts
if (isLiveNews) {
  schemaOrgDefinition['@type'] = 'LiveBlogPosting'
  schemaOrgDefinition['@id'] = '#<id>'
  schemaOrgDefinition.coverageStartTime = singleNews.publish_date
}
```

You _should_ only have a single root-level schema.org ideally though. You could consider just using multiple `@type`'s which is valid.

```ts
const schemaOrgDefinition: any = {
  '@type': isLiveNews ? ['NewsArticle', 'LiveBlogPosting'] : 'NewsArticle',
...restOfMySchema
}
```

**Comment by djixadin** [comment]
hi yes, thanks for the answer. i did initially try that but google structured data doesn't seem to pick it up when in the same schema and all the sites i checked with the LiveBlogPosting live tag they all have separated schema org one for the Article, NewsArticle and another one for LiveBlogPosting. Although its weird that google structured data checker doesnt cover LiveBlogPosting at all.
