### ISSUE TITLE
Schema creation not working in production when used on page

### ISSUE THREAD

**Issue by yingenpass** [harlan-zw/nuxt-schema-org#5]
### Describe the bug

First of all, thank you for this module, the results (if you get them) are really very well thought out.

Unfortunately, it is not possible for me to achieve a working result in production. When I apply `useSchemaOrg` to the `app.vue` file, I get a result that is incomplete without the data that has been added from the pages. If I only use the pages, I get a suitable tag in the head in the end result (the position setting is by the way also ignored in production), but this is not filled and looks faulty:

`<script type="application/ld+json" id="schema-org-graph" nodes="[object Object],[object Object],[object Object],[object Object],[object Object]"></script>`

In addition, I noticed that something also occurs in development that is possibly related to it and/or is not wanted. The fact is that when I use `useSchemaOrg` in development both in `app.vue` and on the pages, I get two `application/ld+json` tags instead of just one. One of them is the one that is generated inside the `app.vue` (incomplete) and the other one that is generated in the pages (complete).

### Reproduction

Not sure

### System Info

```Shell
Nuxt 3.0.0
nuxt-schema-org 2.0.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey, thanks for the issue.

I've pushed out a new version, 2.0.6. Could you try this and let me know if these problems persists?

If so, would you mind providing some of the code you're using so I can attempt to replicate it, otherwise a stackblitz would be amazing.

**Comment by yingenpass** [comment]
Hey, thank you for your quick response and sorry for my late response.

Your updated version definitely removed the duplicate entry. Unfortunately, the one that no longer exists was the right one 😬 What remains, at least for me, is the entry that is generated exclusively from the data in `app.vue`.

Unfortunately, I had to realize that it is probably a problem that is caused by unknown local influences. I could tell by the fact that a Stackblitz works wonderfully. Based on that, I tried switching off and/or commenting out all possible modules as a test, unfortunately without success, the problem persists.

Unfortunately I can't explain it. It may now fall out of the scheme as a bug, but I would still like to ask if you or someone reading along has an idea where such a problem could come from.

**Comment by yingenpass** [comment]
Okay, after some more filtering, I found the culprit. Unfortunately, the data from the pages is not recorded because I use a listener that waits for the page to finish loading and only then releases it via a fade animation triggered by an v-if on the parent, so that its not existing till then. This is probably quite an edge case, but is this something that should be considered to be adjusted?

**Comment by harlan-zw** [comment]
Thanks for sticking with the investigation, seems like it was an annoying one to debug.

Because this data is needed on the initial server render of the HTML page I think you'd need to re-architect it in a way where you're not blocking the render of the schema / content. This is generally the best practice with working with anything you want to be indexed so I think it's out of the scope of the package.

If you want transition between pages you're better off using the classes provided by vue-router rather than not rendering the content.

**Comment by ebrawer** [comment]
I'm trying to understand if I'm facing the same issue...

https://search.google.com/test/rich-results/result?id=UTHSLuE0sAlbE5-CqZnvQw

Nothing detected, but the HTML is correct (has the ld+json, but also the nodes object issue).

**Comment by ebrawer** [comment]
This happens even on a completely static page:

```
<script type="application/ld+json" id="schema-org-graph" data-hid="3437552" nodes="[object Object],[object Object],[object Object]">
```

**Comment by harlan-zw** [comment]
You're most likely not using the latest version of Unhead and/or this Nuxt module.

You should check with `npm why @unhead/schema-org`.

I've created a StackBlitz, please provide a reproduction if you still have issues: https://stackblitz.com/edit/nuxt-starter-z9np1t?file=.gitignore

**Comment by ebrawer** [comment]
> npm why @unhead/schema-org

```
npm why @unhead/schema-org
@unhead/schema-org@1.7.4
node_modules/@unhead/schema-org
  @unhead/schema-org@"^1.7.4" from the root project
  @unhead/schema-org@"^1.7.4" from nuxt-schema-org@3.0.1
  node_modules/nuxt-schema-org
    dev nuxt-schema-org@"^3.0.1" from the root project
```

**Comment by harlan-zw** [comment]
Yes please use the latest version of the module
