### ISSUE TITLE
schemaOrg.default property is unknown

### ISSUE THREAD

**Issue by lucpotage** [harlan-zw/nuxt-schema-org#52]
### Describe the bug

Adding a default property in `schemaOrg` object triggers this error:

> Object literal may only specify known properties, but 'default' does not exist in type 'Partial<ModuleOptions>'. Did you mean to write 'defaults'?

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ufazpz?file=nuxt.config.ts

### System / Nuxt Info

```Shell
- Operating System: Darwin
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      devtools, vite, runtimeConfig, extends, modules, site, schemaOrg, veeValidate
- Runtime Modules:  @nuxthq/studio@1.0.13, @nuxt/image@1.6.0, @nuxt/content@2.12.1, @unocss/nuxt@0.59.4, @vee-validate/nuxt@4.12.6, nuxt-schema-org@3.3.6, nuxt-og-image@3.0.0-rc.53, @nuxtjs/sitemap@5.1.5
- Build Modules:    -
```

**Comment by williarin** [comment]
It's `defaults` with an ending `s`, the documentation mispelled it.

https://github.com/harlan-zw/nuxt-schema-org/blob/main/src/module.ts#L24

**Comment by harlan-zw** [comment]
Thanks!
