### ISSUE TITLE
Types for all define schema methods return `any`

### ISSUE THREAD

**Issue by asokawotulo** [harlan-zw/nuxt-schema-org#60]
### Describe the bug

When hovering over the `defineProduct` function to get the type definition it returns `any`
![Screen Shot 2024-09-20 at 1  40 48](https://github.com/user-attachments/assets/7ced9fd5-0624-4ab3-9bf5-9d946a0bbd8d)

Changing the type import in `.nuxt/types/imports.d.ts` to import from `../../node_modules/@unhead/schema-org` instead of `../../node_modules/@unhead/schema-org/vue` temporarily fixes the issue
![Screen Shot 2024-09-20 at 1  43 12](https://github.com/user-attachments/assets/625db162-34e0-4a19-ae32-d99042452c6e)
![Screen Shot 2024-09-20 at 1  43 39](https://github.com/user-attachments/assets/80cc6515-8736-4de5-ba90-8e40afab9312)

**Comment by asokawotulo** [comment]
I tried to initialize a new project and still had the same issue.

I'm running the following version:
```
nuxt-schema-org 3.4.0
@unhead/schema-org 1.11.6
```

**Comment by harlan-zw** [comment]
This should be fixed in the latest
