### ISSUE TITLE
How to use schema-org with Nuxt Content

### ISSUE THREAD

**Issue by KajKandler** [harlan-zw/nuxt-schema-org#61]
### Details

How to get schema.org JSON+LD markup into pages written with Nuxt Content, specifically Markdown pages

How do I add page-specific schema, such as "author", "about", ..."

What are the ways to connect those two?

- front matter that is picked up?
- do I need to add  MDC components?
  - How do I do this?
- do I need to add a script to the pages/[...slug].vue

Are there any examples for this use case I could follow?

**Comment by harlan-zw** [comment]
Thanks for the suggestion, this is now supported with v3.5.0, please see https://github.com/harlan-zw/nuxt-schema-org/pull/67
