### ISSUE TITLE
Documentation: 'nuxt-og-image' in installation page

### ISSUE THREAD

**Issue by LouisMazel** [harlan-zw/nuxt-schema-org#63]
### Additional context

<img width="773" alt="Capture d’écran 2024-11-12 à 15 43 18" src="https://github.com/user-attachments/assets/ceb523a9-862d-4f7e-b959-762a1ffb23dd">

I wanted to change it in a PR but I don't know where the content of this part is

**Comment by harlan-zw** [comment]
Thanks! Have pushed up a fix
