### ISSUE TITLE
Warning since the v3.4.2

### ISSUE THREAD

**Issue by LouisMazel** [harlan-zw/nuxt-schema-org#64]
### Describe the bug

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/60d7485c-1af3-4095-8de0-eb656ecd46cd">

### System / Nuxt Info

  System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 83.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
    pnpm: 9.12.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 17.6

**Comment by robmontesinos** [comment]
Same here. Added some info on https://github.com/harlan-zw/nuxt-schema-org/pull/55#issuecomment-2484694864

**Comment by ptdev** [comment]
Hi,

Also getting this same error.

Any reason why this issue is closed?

Are there any fixes available?

Cheers

**Comment by LouisMazel** [comment]
@ptdev

**Comment by harlan-zw** [comment]
Sorry for the delay, have pushed up a fix in 3.4.3

**Comment by ptdev** [comment]
Hey, thanks for the update, but unfortunately the fix gives the following error:

```
[nitro 1:27:35 PM]  ERROR  RollupError: node_modules/nuxt-schema-org/dist/runtime/nuxt/util/shared.js (5:2): "injectHead" is not exported by "virtual:#imports", imported by "node_modules/nuxt-schema-org/dist/runtime/nuxt/util/shared.js".


3:   defineOrganization,
4:   definePerson,
5:   injectHead,
     ^
6:   useRoute,
7:   useRuntimeConfig,
```


Repro at https://stackblitz.com/edit/nuxt-starter-zakpee?file=package.json

Cheers

**Comment by LeanderD** [comment]
> Hey, thanks for the update, but unfortunately the fix gives the following error:
> 
> ```
> [nitro 1:27:35 PM]  ERROR  RollupError: node_modules/nuxt-schema-org/dist/runtime/nuxt/util/shared.js (5:2): "injectHead" is not exported by "virtual:#imports", imported by "node_modules/nuxt-schema-org/dist/runtime/nuxt/util/shared.js".
> 
> 
> 3:   defineOrganization,
> 4:   definePerson,
> 5:   injectHead,
>      ^
> 6:   useRoute,
> 7:   useRuntimeConfig,
> ```
> 
> Repro at https://stackblitz.com/edit/nuxt-starter-zakpee?file=package.json
> 
> Cheers

Same here
