### ISSUE TITLE
help: Test schema in staging env

### ISSUE THREAD

**Issue by vuthanhbayit** [harlan-zw/nuxt-schema-org#69]
### 📚 What are you trying to do?

I want my team to test the schema in the staging environment, then robots.txt disables all pages, then the schema is not rendered. What should I do?

### 🔍 What have you tried?

- I created a useSchemaOrgCustomize but it didn't work, inside the module use useSchemaOrg for identity, so I'm missing the Organization schema.

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. In v4.0.4 it will no longer disable the schema.org being generated in non-production envirnments.

**Comment by vuthanhbayit** [comment]
Thank you so much for the quick update and efficient work. Respect!
