### ISSUE TITLE
help: package.json description usage in website body

### ISSUE THREAD

**Issue by jakubednar** [harlan-zw/nuxt-schema-org#70]
### 📚 What are you trying to do?

Hi,
I’ve noticed that nuxt-schema-org injects a global variable __NUXT_SITE_CONFIG__ into the production build and uses the description field from package.json for its Schema.org graph data. I couldn’t find any reference to this behavior in the documentation.

### 🔍 What have you tried?

I tried setting `defaults` option to false but it didn't help. Only removing `description` from package.json solved it.

**Comment by harlan-zw** [comment]
Hi @jakubednar, this is behaviour from Nuxt Site Config. In retrospect this feature was probably not a good one to implement but at this point there isn't a way to remove it without a breaking change which I'd like to avoid for now.

To work around it you can simply set a site description in your Nuxt config.

```ts
export default defineNuxtConfig({
  site: {
    description: 'My cool website which showcases several things that you might enjoy',
  }
})
```
